### ISSUE TITLE
Header is weird and ugly

### ISSUE THREAD

**Issue by mgersh** [learning-unlimited/learning-unlimited.github.io#1]
Old site:
![old_lu](https://cloud.githubusercontent.com/assets/2846855/18423996/caa8b062-7878-11e6-8d7d-0abe3f694c89.png)

New site:
![new_lu](https://cloud.githubusercontent.com/assets/2846855/18424003/d656110c-7878-11e6-957b-d9a302e131ec.png)

**Comment by mgersh** [comment]
Oh right I should probably include useful bug report details or something. This is using Chrome 52 (I'm bad at updates, oops) on Ubuntu.

**Comment by benjaminjkraft** [comment]
Weird, this worked right on my dev server.  I think I know what's wrong though.

**Comment by benjaminjkraft** [comment]
Indeed, that worked!
