### ISSUE TITLE
Some redirects go to wrong URL

### ISSUE THREAD

**Issue by mgersh** [learning-unlimited/learning-unlimited.github.io#9]
For example, https://www.learningu.org/becoming-a-chapter (note lack of trailing slash) redirects to https://learning-unlimited.github.io/becoming-a-chapter/ (note github.io hostname)

**Comment by benjaminjkraft** [comment]
Oh, interesting.  I think this is a bug

**Comment by benjaminjkraft** [comment]
Ok, I think I finally figured out the right combination of CloudFlare and Github Pages settings to get this to work.  We end up redirecting HTTPS -> HTTP -> HTTPS in a few cases, but so it goes.

**Comment by benjaminjkraft** [comment]
Note to self: I might be able to fix this better by removing the CNAME but setting the `url` in jekyll config.  I'll have to see if Github does the right thing then, possibly on a test site.
